name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: [main]
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      # ... (before - run: npm run build-storybook)
      - name: Debug - List contents of src directory
        run: ls -R src
      # This will recursively list all files and folders inside 'src'
      # Look for 'src/components/ui/button/button.tsx' in this output!

      - name: Debug - Print current working directory
        run: pwd

      - name: Debug - Check if button.tsx exists
        run: |
          if [ -f "./src/components/ui/button/button.tsx" ]; then
            echo "button.tsx exists at the expected path!"
          else
            echo "ERROR: button.tsx DOES NOT exist at ./src/components/ui/button/button.tsx"
          fi
      - run: npm run build-storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static